name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.1' # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Deploy to AWS EC2
    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "Deploying application to EC2..."
        ssh -o "StrictHostKeyChecking=no" -i "${KEY}" ${USER}@${HOST} << 'EOF'
          # Stop existing app if running
          pm2 stop all || true
          
          # Navigate to app directory
          cd /ci-cd/ci-cd-node/

          # Pull latest code
          git pull origin master

          # Install dependencies
          npm install

          # Restart application
          pm2 start index.js
        EOF
