name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Deploy to EC2
    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "Deploying application to EC2..."

        # Create a temporary file for the private key
        echo "${{ secrets.EC2_KEY }}" > private_key.pem
        chmod 600 private_key.pem  # Make the key file read-only

        # SSH into EC2 and execute commands
        ssh -o "StrictHostKeyChecking=no" -i private_key.pem ${USER}@${HOST} << 'EOF'
          # Add the repository directory as a safe directory for Git
          git config --global --add safe.directory /home/ubuntu/ci-cd/ci-cd-node

          # Navigate to the application folder
          cd /home/ubuntu/ci-cd/ci-cd-node || exit

          # Pull the latest changes
          git pull origin master

          # Install dependencies and restart the application
          npm install
          pm2 restart index.js || pm2 start index.js
        EOF

        # Remove the private key file after use
        rm private_key.pem

